### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by aknot242**

### CODE REVIEW

**Review by shawnhankim — APPROVED** [review]
Oh, @aknot242 : Thank you so much for this PR. 👍

**Comment by shawnhankim** [comment]
@aknot242 : I would appreciate it if you could feel free to merge this PR when you are ready.
Cc. @pmoghef5

**Comment by aknot242** [comment]
@shawnhankim - I don't have the permission to merge into this repo.

**Comment by shawnhankim** [comment]
> @shawnhankim - I don't have the permission to merge into this repo.

@aknot242 - Oh, I see! I have added you to the member list with the permission. The status is pending so you can accept my invitation. Let me know if you can't access. Thanks.

**Pull request merged**
